name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install dependencies
        run: cargo build --release
      - name: Run tests
        run: cargo test
      - name: Run Clippy
        run: cargo clippy -- -D warnings
